name: storybook_device_preview
description: A plugin for device_preview package that allows to embed storybook_flutter.
version: 0.2.0+2
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_preview: ^0.7.1
  flutter:
    sdk: flutter
  storybook_flutter: ^0.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.0

flutter:
