name: storybook_device_preview
description: A new Flutter project.
version: 0.1.0
homepage: https://github.com/ookami-kb/storybook_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_preview: ^0.7.1
  flutter:
    sdk: flutter
  storybook_flutter: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mews_pedantic: ^0.2.0

flutter:
